# Generated by Django 3.2.6 on 2021-08-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationCommands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('juniper_command', models.CharField(max_length=500)),
                ('cisco_command', models.CharField(max_length=500)),
                ('related_to', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'migration_commands',
            },
        ),
    ]
