# Generated by Django 3.2.7 on 2021-09-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiscoLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('input_file', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cisco_logs',
            },
        ),
        migrations.CreateModel(
            name='MigrationLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_vendor', models.CharField(max_length=10)),
                ('input_file', models.CharField(max_length=255)),
                ('migrated_file', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'migration_logs',
            },
        ),
    ]
